name: Python Release

on:
  workflow_run:
    workflows:
      - Python Release Verify
    types:
      - completed

concurrency:
  group: python-release-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

env:
  UV_EXTRA_INDEX_URL: https://pypi.nvidia.com

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: python-release-dist
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
